data:
  train_data_source: "mixed"

run:
  experiment_name: 'trauma_study'
  note: ""
  run_suffix: "_mixed_training_data"

hp_rf:
  n_estimators: 100
  min_samples_leaf: 5

hp_ab:
  n_estimators: 100
  learning_rate: 0.4

hp_xgb: 
  eval_metric: "auc"
  max_depth: 10

hp_gam:
  outer_bags: 25
  inner_bags: 25
  max_leaves: 5
  max_bins: 64
  seed: 42

