data:
  train_data_source: "US"

run:
  experiment_name: 'trauma'
  note: ""
  run_suffix: "_US"

hp_rf:
  n_estimators: 50
  min_samples_leaf: 5
  max_depth: 10

hp_ab:
  n_estimators: 50
  learning_rate: 0.4

hp_xgb: 
  eval_metric: "auc"
  max_depth: 10

hp_gam:
  outer_bags: 8
  inner_bags: 0
  max_leaves: 5
  max_bins: 256
  seed: 42

