cat_names = ['SEX', 'TEACHINGSTATUS', 'BEDSIZE', 'VERIFICATIONLEVEL',
            'CC_ADHD', 'CC_ALCOHOLISM', 'CC_ANGINAPECTORIS'
             , 'CC_ANTICOAGULANT', 'CC_BLEEDING', 'CC_CHEMO', 'CC_CIRRHOSIS', 'CC_COPD', 'CC_CVA', 'CC_DEMENTIA'
             , 'CC_DIABETES', 'CC_CHF', 'CC_HYPERTENSION', 'CC_MI', 'CC_PAD', 'CC_MENTALPERSONALITY', 'CC_RENAL'
             , 'CC_SMOKING', 'CC_STEROID', 'CC_SUBSTANCEABUSE',
            'CAUSE']

cont_names = ['AGEYEARS', 'WEIGHT', 'HEIGHT', 'EMSSBP', 'EMSTOTALGCS', "TOTALGCS", 'SBP', 'PULSERATE', 'TEMPERATURE', 'PULSEOXIMETRY', 'RESPIRATORYRATE', 'ISS_05', 'diff_GCS', 'diff_SBP']

ais_names= ['HEAD_1', 'HEAD_2', 'HEAD_3', 'HEAD_4', 'HEAD_5', 'HEAD_6',
       'HEAD_9', 'HEAD_NA', 'FACE_1', 'FACE_2', 'FACE_3', 'FACE_4', 'FACE_5',
       'FACE_9', 'FACE_NA', 'NECK_1', 'NECK_2', 'NECK_3', 'NECK_4', 'NECK_5',
       'NECK_6', 'NECK_9', 'THORAX_1', 'THORAX_2', 'THORAX_3', 'THORAX_4',
       'THORAX_5', 'THORAX_6', 'THORAX_9', 'THORAX_NA', 'ABDOMEN_1',
       'ABDOMEN_2', 'ABDOMEN_3', 'ABDOMEN_4', 'ABDOMEN_5', 'ABDOMEN_6',
       'ABDOMEN_9', 'ABDOMEN_NA', 'SPINE_1', 'SPINE_2', 'SPINE_3', 'SPINE_4',
       'SPINE_5', 'SPINE_6', 'SPINE_9', 'SPINE_NA', 'UPPER_EXT_1',
       'UPPER_EXT_2', 'UPPER_EXT_3', 'UPPER_EXT_4', 'UPPER_EXT_5',
       'UPPER_EXT_6', 'UPPER_EXT_9', 'UPPER_EXT_NA', 'LOWER_EXT_1',
       'LOWER_EXT_2', 'LOWER_EXT_3', 'LOWER_EXT_4', 'LOWER_EXT_5',
       'LOWER_EXT_6', 'LOWER_EXT_9', 'LOWER_EXT_NA', 'UNSPEC_1', 'UNSPEC_2',
       'UNSPEC_3', 'UNSPEC_4', 'UNSPEC_5', 'UNSPEC_6', 'UNSPEC_9',
       'UNSPEC_NA']

cat_names =cat_names+ais_names

target = ['DECEASED', 'LOS48HOURSPLUS']

resampling_dict= {"DECEASED":{"ss":0.5, "kn":3, "x":None, "y":None}}    

long_names_dict = { 'ABDOMEN_1': 'Minor Abdominal Injury',
                     'ABDOMEN_2': 'Moderate Abdominal Injury',
                     'ABDOMEN_3': 'Serious Abdominal Injury',
                     'ABDOMEN_4': 'Severe Abdominal Injury',
                     'ABDOMEN_5': 'Critical Abdominal Injury',
                     'ABDOMEN_6': 'Maximum Abdominal Injury',
                     'ABDOMEN_9': 'Abdominal Injury (NFS)',
                     'ABDOMEN_NA': 'Abdomen injury without severity specification',
                     'AGEYEARS': 'Age in years',
                     'AIS': 'Abbreviated injury scale (AIS)',
                     'BEDSIZE': 'Hospital count of beds',
                     'CAUSE': 'Primary cause of injury',
                     'CC_ADHD': 'Comorbid condition: ADHD',
                     'CC_ALCOHOLISM': 'Comorbid condition: Alcoholism',
                     'CC_ANGINAPECTORIS': 'Comorbid condition: Angina pectoris',
                     'CC_ANTICOAGULANT': 'Comorbid condition: Anticoagulant treatment',
                     'CC_BLEEDING': 'Comorbid condition: Bleeding disorders',
                     'CC_CHEMO': 'Comorbid condition: Chemotherapy',
                     'CC_CHF': 'Comorbid condition: Congestive heart failure',
                     'CC_CIRRHOSIS': 'Comorbid condition: Cirrhosis',
                     'CC_COPD': 'Comorbid condition: Chronic obstructive pulmonary disease',
                     'CC_CVA': 'Comorbid condition: Cerebrovascular accident',
                     'CC_DEMENTIA': 'Comorbid condition: Dementia',
                     'CC_DIABETES': 'Comorbid condition: Diabetes (type 1 and 2)',
                     'CC_HYPERTENSION': 'Comorbid condition: Hypertension',
                     'CC_MENTALPERSONALITY': 'Comorbid condition: Mental disorders (schizophrenia, bipolar disorder, major depressive disorder, social anxiety, PTSD, antisocial personality disorder)',
                     'CC_MI': 'Comorbid condition: Myocardial infarction',
                     'CC_PAD': 'Comorbid condition: Peripheral arterial disease',
                     'CC_RENAL': 'Comorbid condition: Chronic renal failure',
                     'CC_SMOKING': 'Comorbid condition: Smoking tobacco every day or some days within past 12 months',
                     'CC_STEROID': 'Comorbid condition: Regular administration of oral or parental corticosteroid medications',
                     'CC_SUBSTANCEABUSE': 'Comorbid condition: Documented substance abuse (cannabis, hallucinogens, inhalents, opiods, sedatives, other)',
                     'DECEASED': 'In-hospital mortality',
                     'EMSSBP': 'Pre-hospital systolic blood pressure',
                     'EMSTOTALGCS': 'Pre-hospital Glasgow Coma Score (total)',
                     'FACE_1': 'Minor Face Injury',
                     'FACE_2': 'Moderate Face Injury',
                     'FACE_3': 'Serious Face Injury',
                     'FACE_4': 'Severe Face Injury',
                     'FACE_5': 'Critical Face Injury',
                     'FACE_9': 'Face Injury (NFS)',
                     'FACE_NA': 'Face injury without severity specification',
                     'HEAD_1': 'Minor Head Injury',
                     'HEAD_2': 'Moderate Head Injury',
                     'HEAD_3': 'Serious Head Injury',
                     'HEAD_4': 'Severe Head Injury',
                     'HEAD_5': 'Critical Head Injury',
                     'HEAD_6': 'Maximum Head Injury',
                     'HEAD_9': 'Head Injury (NFS)',
                     'HEAD_NA': 'Head injury without severity specification',
                     'HEIGHT': 'Height in cm',
                     'ISS_05': 'Injury severity score derived from AIS',
                     'LOS48HOURSPLUS': 'Total length of stay longer than 2 days from admission',
                     'LOSDays': 'Length of hospital stay in days',
                     'LOWER_EXT_1': 'Minor Lower Extremity Injury',
                     'LOWER_EXT_2': 'Moderate Lower Extremity Injury',
                     'LOWER_EXT_3': 'Serious Lower Extremity Injury',
                     'LOWER_EXT_4': 'Severe Lower Extremity Injury',
                     'LOWER_EXT_5': 'Critical Lower Extremity Injury',
                     'LOWER_EXT_6': 'Maximum Lower Extremity Injury',
                     'LOWER_EXT_9': 'Lower Extremity Injury (NFS)',
                     'LOWER_EXT_NA': 'Lower extremity injury without severity specification',
                     'NECK_1': 'Minor Neck Injury',
                     'NECK_2': 'Moderate Neck Injury',
                     'NECK_3': 'Serious Neck Injury',
                     'NECK_4': 'Severe Neck Injury',
                     'NECK_5': 'Critical Neck Injury',
                     'NECK_6': 'Maximum Neck Injury',
                     'NECK_9': 'Neck Injury (NFS)',
                     'PENETRATION_INJ': 'Pentrative injury',
                     'PULSEOXIMETRY': 'In-hospital pulseoximetry',
                     'PULSERATE': 'In-hospital pulserate (BPM)',
                     'RESPIRATORYRATE': 'In-hospital respiratory rate (BPM)',
                     'SBP': 'In-hospital systolic blood pressure',
                     'SEX': 'Sex (female, male)',
                     'SPINE_1': 'Minor Spine Injury',
                     'SPINE_2': 'Moderate Spine Injury',
                     'SPINE_3': 'Serious Spine Injury',
                     'SPINE_4': 'Severe Spine Injury',
                     'SPINE_5': 'Critical Spine Injury',
                     'SPINE_6': 'Maximum Spine Injury',
                     'SPINE_9': 'Spine Injury (NFS)',
                     'SPINE_NA': 'Spine injury without severity specification',
                     'TEACHINGSTATUS': 'Hospital teaching status',
                     'TEMPERATURE': 'In-hospital temperature in celsius',
                     'THORAX_1': 'Minor Thoracic Injury',
                     'THORAX_2': 'Moderate Thoracic Injury',
                     'THORAX_3': 'Serious Thoracic Injury',
                     'THORAX_4': 'Severe Thoracic Injury',
                     'THORAX_5': 'Critical Thoracic Injury',
                     'THORAX_6': 'Maximum Thoracic Injury',
                     'THORAX_9': 'Thoracic Injury (NFS)',
                     'THORAX_NA': 'Thorax injury without severity specification',
                     'TOTALGCS': 'In-hospital Glasgow Coma Score (total)',
                     'UNSPEC_1': 'Minor Unspecified Injury',
                     'UNSPEC_2': 'Moderate Unspecified Injury',
                     'UNSPEC_3': 'Serious Unspecified Injury',
                     'UNSPEC_4': 'Severe Unspecified Injury',
                     'UNSPEC_5': 'Critical Unspecified Injury',
                     'UNSPEC_6': 'Maximum Unspecified Injury',
                     'UNSPEC_9': 'Unspecified Injury (NFS)',
                     'UNSPEC_NA': 'Unspecified injury without severity specification',
                     'UPPER_EXT_1': 'Minor Upper Extremity Injury',
                     'UPPER_EXT_2': 'Moderate Upper Extremity Injury',
                     'UPPER_EXT_3': 'Serious Upper Extremity Injury',
                     'UPPER_EXT_4': 'Severe Upper Extremity Injury',
                     'UPPER_EXT_5': 'Critical Upper Extremity Injury',
                     'UPPER_EXT_6': 'Maximum Upper Extremity Injury',
                     'UPPER_EXT_9': 'Upper Extremity Injury (NFS)',
                     'UPPER_EXT_NA': 'Upper extremity injury without severity specification',
                     'VERIFICATIONLEVEL': 'Hospital ACS Trauma Center Verification level',
                     'WEIGHT': 'Weight in kg',
                     'diff_GCS': 'Absolute difference between\npre- and in-hospital\nGlasgow Coma Score',
                     'diff_SBP': 'Absolute difference between\npre- and in-hospital systolic\nblood pressure measurement'}

def col_selector(df, target): 
    try:
        return df[cat_names+cont_names+ais_names+target].copy(deep=True)
    except:
        return df[cat_names+cont_names+ais_names+[target,]].copy(deep=True)

