data:
  train_data_source: "US"
  resampling: "SMOTETomek"
run:
  experiment_name: 'trauma'
  note: "study_test_v3"
  run_suffix: "_US"

hp_rf:
  n_estimators: 100
  min_samples_leaf: 5
  max_depth: 10

hp_ab:
  n_estimators: 50
  learning_rate: 0.4

hp_xgb: 
  eval_metric: "aucpr"
  max_depth: 5

hp_gam:
  outer_bags: 8
  inner_bags: 0
  max_leaves: 5
  max_bins: 256
  seed: 42

